[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixelshop"
version = "2024.4.0b4"
requires-python = ">=3.12"
readme = "README.md"
license = {file = "LICENSE"}

[tool.setuptools]
packages = ["pixelshop"]
